// noinspection JSXNamespaceValidation,HtmlUnknownTarget,JSUnresolvedVariable

import Head from 'next/head'

export default function Home(props) {
  return (
    <div>
      <Head>
        <title>Time of Day</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Time of day</h1>
        <p>WorldTimeApi says the time of day is: {props.timeOfDay}</p>
      </main>
    </div>
  )
}

export async function getStaticProps() {
  const res = await fetch('https://worldtimeapi.org/api/timezone/America/Edmonton');
  const resJson = await res.json();

  return {
    props: {
      timeOfDay: resJson.datetime,
    },
    revalidate: 10,
  }
}
